function [parms, hyperparms, thetaprior] = loadFreeDriftParmSettings(model)

%% Drift rates
v1 = logit(.7);
v1_mu = 0; v1_sigma = 1;

v2 = logit(.7);
v2_mu = 0; v2_sigma = 1;

v3 = logit(.7);
v3_mu = 0; v3_sigma = 1;

v4 = logit(.7);
v4_mu = 0; v4_sigma = 1;

v5 = logit(.3);
v5_mu = 0; v5_sigma = 1;

v6 = logit(.3);
v6_mu = 0; v6_sigma = 1;

v7 = logit(.3);
v7_mu = 0; v7_sigma = 1;

v8 = logit(.3);
v8_mu = 0; v8_sigma = 1;

v9 = logit(.3);
v9_mu = 0; v9_sigma = 1;

%% LBA parms
%% Startpoint
A    = log(.35);  
A_mu = log(.35); A_sigma = .2;

%% A boundary minus start point
bMa1 = log(.25); % Threshold minus startpoint
bMa1_mu = log(.25); bMa1_sigma = 1;

%% B boundary minus start point
bMa2 = log(.25); % Threshold minus startpoint
bMa2_mu = log(.25); bMa2_sigma = 1;

%% Drift rate variability
s   = log(.25);  % Drift variability
s_mu = log(.25); s_sigma = .5;

%% Non-decision time
t0    = log(.22);  
t0_mu = log(.22); t0_sigma = .2;

%% Parm structure
% Set up structure which hold the parameters for that model (need
% one section for each model with different parameterization)
parms = struct(...
    'v1', v1,...
    'v2', v2,...
    'v3', v3,...
    'v4', v4,...
    'v5', v5,...
    'v6', v6,...
    'v7', v7,...
    'v8', v8,...
    'v9', v9,...
    'A', A,...
    'bMa1', bMa1,...
    'bMa2', bMa2,...
    's', s,...
    't0', t0);

hyperparms = struct(...
    'v1_mu', v1_mu,...
    'v1_sigma', v1_sigma,...
    'v2_mu', v2_mu,...
    'v2_sigma', v2_sigma,...
    'v3_mu', v3_mu,...
    'v3_sigma', v3_sigma,...
    'v4_mu', v4_mu,...
    'v4_sigma', v4_sigma,...
    'v5_mu', v5_mu,...
    'v5_sigma', v5_sigma,...
    'v6_mu', v6_mu,...
    'v6_sigma', v6_sigma,...
    'v7_mu', v7_mu,...
    'v7_sigma', v7_sigma,...
    'v8_mu', v8_mu,...
    'v8_sigma', v8_sigma,...
    'v9_mu', v9_mu,...
    'v9_sigma', v9_sigma,...    
    'A_mu', A_mu,...
    'A_sigma', A_sigma,...
    'bMa1_mu', bMa1_mu,...
    'bMa1_sigma', bMa1_sigma,...
    'bMa2_mu', bMa2_mu,...
    'bMa2_sigma', bMa2_sigma,...
    's_mu', s_mu,...
    's_sigma', s_sigma,...
    't0_mu', t0_mu,...
    't0_sigma', t0_sigma);

% Each parameter has two hyperparms
thetaprior = [...
    v1_mu, v1_sigma;
    v2_mu, v2_sigma;
    v3_mu, v3_sigma;
    v4_mu, v4_sigma;
    v5_mu, v5_sigma;
    v6_mu, v6_sigma;
    v7_mu, v7_sigma;
    v8_mu, v8_sigma;
    v9_mu, v9_sigma;
    A_mu, A_sigma;
    bMa1_mu, bMa1_sigma;
    bMa2_mu, bMa2_sigma;
    s_mu, s_sigma;
    t0_mu, t0_sigma];